name: limit
main: Aleondev\Al\Main
version: 1.0.0
api: [3.0.0,4.0.0]
load: POSTWORLD
author: Aleondev
description: "ein DC Link Pl"

commands:
  DC:
    description: ยง4Generiert Ein DC Link
    usage: "/DC "
    permission: DC.command
