name: limit
main: Aleondev\Al\Main
version: 1.0.0
api: [3.0.0,4.0.0]
load: POSTWORLD
author: Aleondev
description: "ein wünsche erfüllen plugin"

commands:
  limit:
    description: §elimit §4command §fBy Aleondev
    usage: "/limit"
    permission: limmit.command
